name: maven build

on:
  push:
    branches:
    - master
#jobs:
#  # This workflow contains a single job called "build"
#  build:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/setup-java@v2
#      with:
#        java-version: '11'
#        distribution: 'adopt'
#    - name: Publish package
#      run: mvn --debug deploy
#      env:
#        GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}

#    - name: maven build
#      run: mvn package
#    - name: scp
#      uses: garygrossgarten/github-action-scp@release
#      with:
#        local: /home/runner/work/action-test/action-test/registry-server/target/points-registry-server.jar
#        remote: /opt/action-test
#        host: 10.128.10.21
#        username: root
#        password: hxd@20191231
#        port: 22
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GIST_TOKEN }}
        registry: docker.pkg.github.com
        repository: /lhnlny/repostitory/test-image
        tag_with_ref: true


