name: Publish package to the Maven Central Repository

on:
  push:
    branches:
    - master
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    #获取master分支
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1  #使用官方脚本创建java环境
      with:
        java-version: 1.8
    - name: Build with Maven
        run: mvn clean package
    - name: scp
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /
        remote: /opt/action-test
        host: ${{ secrets.DOCKER_IP }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}


